#!/bin/sh

if [ -L "/var/jb" ]; then
    launchctl load /var/jb/Library/LaunchDaemons/com.julioverne.screendumpd.plist
else
    launchctl load /Library/LaunchDaemons/com.julioverne.screendumpd.plist
fi

exit 0;
