#!/bin/sh

if [ -L "/var/jb" ]; then
    launchctl unload /var/jb/Library/LaunchDaemons/ru.mostmodest.screendumpd.plist
else
    launchctl unload /Library/LaunchDaemons/ru.mostmodest.screendumpd.plist
fi

exit 0;
